// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
)

type ApiKey struct {
	ID         string         `json:"id"`
	ExpiryDate sql.NullString `json:"expiry_date"`
}

type Data struct {
	ID         int32         `json:"id"`
	CreatedAt  sql.NullTime  `json:"created_at"`
	UpdatedAt  sql.NullTime  `json:"updated_at"`
	DataTypeID sql.NullInt32 `json:"data_type_id"`
	Value      float64       `json:"value"`
}

type DataType struct {
	ID       int32          `json:"id"`
	Key      string         `json:"key"`
	Unit     string         `json:"unit"`
	DeviceID sql.NullString `json:"device_id"`
}

type Device struct {
	ID        string       `json:"id"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
	Name      string       `json:"name"`
	Location  string       `json:"location"`
}
